---
- hosts: all
  remote_user: digitalocean
  vars:
    vnc_pass: foobar
    start_vnc_server_script: startvnc.sh
  tasks:
    - name: install xfce4
      apt: name=xfce4 update_cache=yes
      become: yes
    - name: install rsync
      apt: name=rsync
      become: yes
    - name: install tightvncserver
      apt: name=tightvncserver
      become: yes
    - name: install chromium
      apt: name=chromium
      become: yes
    - name: create .vnc
      file: path=~/.vnc state=directory mode=0700
    - name: set the vnc password
      shell: echo {{vnc_pass}} |vncpasswd -f > ~/.vnc/passwd
    - name: set unreadable
      file: path=~/.vnc/passwd mode=0600
    - name: put a script which starts a vncserver
      copy: src={{start_vnc_server_script}} dest=~/ mode="u+x"
