---
- hosts: all
  remote_user: digitalocean
  vars:
    vnc_pass: foobar
    start_vnc_server_script: startvnc.sh
  tasks:
    - name: install xfce4
      apt: name=xfce4 update_cache=yes
      become: yes
    - name: install rsync
      apt: name=rsync
      become: yes
    - name: install tightvncserver
      apt: name=tightvncserver
      become: yes
    - name: install chromium
      apt: name=chromium
      become: yes
    - name: directory
      file: path=~/.vnc state=directory mode=0700
    - name: shell
      shell: echo {{vnc_pass}} |vncpasswd -f > ~/.vnc/passwd
    - name: user
      file: path=~/.vnc/passwd mode=0600
  #    - name: z
  #    shell: vncserver :1
  #  - name: down
  #    shell: vncserver -kill :1
  #  - name: a
  #    shell: echo exec startxfce4  >> ~/.vnc/xstartup 
  #  - name: a
  #    shell: pwd
    - name: put startup vncserver script
      copy: src={{start_vnc_server_script}} dest=~/ mode="u+x"
